[package]
name = "reos"
version = "0.1.0"
edition = "2021"

[lib]
name = "reos"


[dependencies] 
serde = { version = "1.0.217", features = ["derive"] }
ndarray = { version = "0.16.1", features = ["serde"] }
serde_json = "1.0"
thiserror = "2"
approx = "0.5"